#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import struct
from collections import defaultdict
from pathlib import Path


SEMANTIC_NAMES = {
    0x81C00020: "element_table_entry",
    0x81C00050: "runtime_bootstrap",
    0x81C001A0: "load_dlx_resource_file",
    0x81C002F8: "load_dlx_resource_by_index",
    0x81C004BC: "get_dlx_resource",
    0x81C00648: "resource_noop",
    0x81C00654: "free_loaded_dlx_resource_payload",
    0x81C0069C: "free_dlx_resource_table",
    0x81C006D0: "element_detail_window_proc",
    0x81C00BEC: "main_window_send_text_block",
    0x81C00C20: "main_window_send_dict_command_block",
    0x81C00C3C: "main_window_trace_background_block",
    0x81C00C58: "main_window_create_draw_object_block",
    0x81C00C78: "main_window_request_refresh_block",
    0x81C00CA0: "main_window_trace_create_failure_block",
    0x81C00CCC: "main_window_seek_description_block",
    0x81C00CF4: "main_window_read_description_block",
    0x81C00D1C: "main_window_close_description_block",
    0x81C00D48: "main_window_navigation_block",
    0x81C00DE4: "main_window_begin_draw_block",
    0x81C00E48: "main_window_draw_resource_block",
    0x81C00EE8: "main_window_close_detail_block",
    0x81C00F48: "main_window_destroy_object_block",
    0x81C00F5C: "main_window_stop_frame_block",
    0x81C00F7C: "draw_current_element_tile",
    0x81C01204: "draw_current_element_highlight",
    0x81C014DC: "periodic_table_window_proc",
    0x81C01A98: "detail_notify_block",
    0x81C01AB4: "detail_begin_frame_draw_block",
    0x81C01AD0: "detail_present_after_draw_block",
    0x81C01B04: "detail_delay_after_draw_block",
    0x81C01B38: "detail_present_block",
    0x81C01B54: "detail_finish_draw_block",
    0x81C01C08: "detail_begin_redraw_block",
    0x81C01C24: "detail_present_redraw_block",
    0x81C01C58: "detail_scroll_delay_block",
    0x81C01D3C: "detail_open_hx_block",
    0x81C01D68: "detail_trace_open_failure_block",
    0x81C01D88: "detail_seek_hx_block",
    0x81C01DB0: "detail_read_offset_block",
    0x81C01DDC: "detail_trace_offset_block",
    0x81C01DFC: "detail_seek_text_block",
    0x81C01E24: "detail_read_text_block",
    0x81C01F2C: "detail_register_frame_block",
    0x81C01F58: "detail_event_poll_block",
    0x81C01F74: "detail_event_step_block",
    0x81C01F88: "detail_event_dispatch_block",
    0x81C02084: "detail_begin_object_draw_block",
    0x81C020D8: "detail_end_object_draw_block",
    0x81C0216C: "detail_stop_frame_block",
    0x81C02188: "detail_release_frame_block",
    0x81C0218C: "element_table_main",
    0x81C0240C: "load_hx_offset_table",
    0x81C02598: "load_element_description",
    0x81C026C0: "run_standard_window",
    0x81C027D0: "local_memchr",
    0x81C0280C: "local_sprintf",
    0x81C02854: "local_strlen",
    0x81C02884: "local_strtol",
    0x81C02AD8: "local_atoi",
    0x81C02AF8: "local_vsprintf",
    0x81C02B60: "local_memset",
    0x81C02BD0: "local_format_core",
    0x81C03320: "local_crt_init",
    0x81C03480: "local_isdigit",
    0x81C034A0: "local_isspace",
    0x81C034D0: "local_toupper",
    0x81C034F0: "local_malloc",
    0x81C03668: "local_heap_init",
    0x81C036B8: "local_malloc_zero_probe",
    0x81C036E0: "local_shift_pairs_back",
}


FUNCTION_COMMENTS = {
    0x81C00020: "BDA 入口：初始化运行时接口表后进入应用主函数。",
    0x81C00050: "清零 BSS，缓存 RES/GUI/SYS/FS/MEM 五张系统 API 表并输出诊断信息。",
    0x81C001A0: "打开并解析 DLX 文件，分配应用私有资源表。",
    0x81C002F8: "从 DLX 中按 1 基索引读取单个资源，并返回状态、类型、大小和数据指针。",
    0x81C004BC: "按索引取得完整 VX 资源块地址。",
    0x81C00648: "空操作回调，可能是保留的窗口/资源钩子。",
    0x81C00654: "释放单资源加载结果中的数据指针，并将该指针清零。",
    0x81C0069C: "释放应用私有 DLX 资源表。",
    0x81C006D0: "元素详情窗口过程；创建 dictview、读取当前元素正文并绘制详情页边栏。",
    0x81C00F7C: "根据当前元素索引绘制元素小图或图集中的局部区域。",
    0x81C01204: "在周期表背景上绘制当前元素的定位与高亮。",
    0x81C014DC: "顶层周期表窗口过程；主函数将该地址写入窗口描述符。",
    0x81C0218C: "应用主函数：选择 DLX、加载 HX 数据、创建主窗口并运行事件循环。",
    0x81C0240C: "读取 HX 文件中的 114 个 24 位偏移，构造元素正文偏移表。",
    0x81C02598: "按元素索引读取 HX 正文到共享缓冲区。",
    0x81C026C0: "创建标准窗口，运行 poll/step/dispatch 事件循环，最后关闭窗口。",
    0x81C027D0: "本地 memchr 实现。",
    0x81C0280C: "本地 sprintf 风格包装函数。",
    0x81C02854: "本地 strlen 实现。",
    0x81C02884: "本地 strtol 实现，支持空白、符号和多进制。",
    0x81C02AD8: "本地 atoi 包装：以十进制调用 strtol。",
    0x81C02AF8: "另一套格式化字符串包装，参数布局仍需动态确认。",
    0x81C02B60: "本地 memset；候选范围尾部还包含相邻的复制辅助代码。",
    0x81C02BD0: "printf/sprintf 共用的格式化核心，通过字符输出回调写结果。",
    0x81C03320: "初始化本地 C 运行时状态、格式化输出对象和小型堆。",
    0x81C03480: "数字字符判断，返回原字符或零。",
    0x81C034A0: "空白字符判断，覆盖空格和 ASCII 9..13。",
    0x81C034D0: "本地 toupper：将 a..z 转换为 A..Z。",
    0x81C034F0: "应用内置的小型堆分配器。",
    0x81C03668: "初始化并对齐内置堆的起止地址和空闲链状态。",
    0x81C036B8: "无参数调用内置分配器；寄存器形状等价于 local_malloc(0)。",
    0x81C036E0: "将若干 8 字节描述符向低地址移动一项；后续无序言辅助块不并入本函数。",
}


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def load_navigation_pairs(source: Path) -> list[tuple[int, int]]:
    """Read the 119 two-word neighbor records at VA 0x81c03fb8."""
    data = source.read_bytes()
    table_offset = 0xD590
    table_size = 119 * 8
    if len(data) < table_offset + table_size:
        raise ValueError(f"BDA is too small for navigation table: {source}")
    return [
        struct.unpack_from("<II", data, table_offset + index * 8)
        for index in range(119)
    ]


def emit_system_header(output: Path) -> None:
    lines = [
        "#ifndef ELEMENT_TABLE_RECONSTRUCTED_SYSTEM_H",
        "#define ELEMENT_TABLE_RECONSTRUCTED_SYSTEM_H",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "typedef uintptr_t word_t;",
        "typedef uint32_t ApiTable;",
        "",
        "/* BDA 启动代码从映像基址 0x81c00000 取得这五张函数表。 */",
        "typedef struct SystemApiContext {",
        "    ApiTable *res;",
        "    ApiTable *gui;",
        "    ApiTable *sys;",
        "    ApiTable *fs;",
        "    ApiTable *mem;",
        "} SystemApiContext;",
        "",
        "extern SystemApiContext g_system_api;",
        "",
        "typedef word_t (*SystemCall4)(word_t, word_t, word_t, word_t);",
        "typedef word_t (*SystemCall8)(word_t, word_t, word_t, word_t,",
        "                              word_t, word_t, word_t, word_t);",
        "typedef word_t (*SystemCall9)(word_t, word_t, word_t, word_t,",
        "                              word_t, word_t, word_t, word_t, word_t);",
        "typedef word_t (*SystemCall11)(word_t, word_t, word_t, word_t,",
        "                               word_t, word_t, word_t, word_t,",
        "                               word_t, word_t, word_t);",
        "",
        "/* 按字节偏移从系统表取函数。参数原型未知时统一保留四寄存器 ABI。 */",
        "static inline word_t system_call4(ApiTable *table, uint32_t offset,",
        "                                  word_t a0, word_t a1, word_t a2, word_t a3)",
        "{",
        "    SystemCall4 fn;",
        "    if (!table)",
        "        return 0;",
        "    fn = (SystemCall4)(uintptr_t)table[offset / 4u];",
        "    return fn ? fn(a0, a1, a2, a3) : 0;",
        "}",
        "",
        "static inline word_t system_call8(ApiTable *table, uint32_t offset,",
        "                                  word_t a0, word_t a1, word_t a2, word_t a3,",
        "                                  word_t a4, word_t a5, word_t a6, word_t a7)",
        "{",
        "    SystemCall8 fn;",
        "    if (!table)",
        "        return 0;",
        "    fn = (SystemCall8)(uintptr_t)table[offset / 4u];",
        "    return fn ? fn(a0, a1, a2, a3, a4, a5, a6, a7) : 0;",
        "}",
        "",
        "static inline word_t system_call9(ApiTable *table, uint32_t offset,",
        "                                  word_t a0, word_t a1, word_t a2, word_t a3,",
        "                                  word_t a4, word_t a5, word_t a6, word_t a7, word_t a8)",
        "{",
        "    SystemCall9 fn;",
        "    if (!table)",
        "        return 0;",
        "    fn = (SystemCall9)(uintptr_t)table[offset / 4u];",
        "    return fn ? fn(a0, a1, a2, a3, a4, a5, a6, a7, a8) : 0;",
        "}",
        "",
        "static inline word_t system_call11(ApiTable *table, uint32_t offset,",
        "                                   word_t a0, word_t a1, word_t a2, word_t a3,",
        "                                   word_t a4, word_t a5, word_t a6, word_t a7,",
        "                                   word_t a8, word_t a9, word_t a10)",
        "{",
        "    SystemCall11 fn;",
        "    if (!table)",
        "        return 0;",
        "    fn = (SystemCall11)(uintptr_t)table[offset / 4u];",
        "    return fn ? fn(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10) : 0;",
        "}",
        "",
        "/* 文件系统 API。 */",
        "static inline word_t system_fs_open(const char *path, const char *mode)",
        "{ return system_call4(g_system_api.fs, 0x000, (word_t)path, (word_t)mode, 0, 0); }",
        "static inline word_t system_fs_close(word_t file)",
        "{ return system_call4(g_system_api.fs, 0x004, file, 0, 0, 0); }",
        "static inline word_t system_fs_read(void *dst, size_t size, size_t count, word_t file)",
        "{ return system_call4(g_system_api.fs, 0x008, (word_t)dst, size, count, file); }",
        "static inline word_t system_fs_seek(word_t file, uint32_t offset, uint32_t origin)",
        "{ return system_call4(g_system_api.fs, 0x010, file, offset, origin, 0); }",
        "",
        "/* 内存与资源诊断 API。 */",
        "static inline void *system_mem_alloc(size_t size)",
        "{ return (void *)system_call4(g_system_api.mem, 0x008, size, 0, 0, 0); }",
        "static inline void system_mem_free(void *ptr)",
        "{ (void)system_call4(g_system_api.mem, 0x00c, (word_t)ptr, 0, 0, 0); }",
        "static inline word_t system_res_trace(const char *format, word_t value)",
        "{ return system_call4(g_system_api.res, 0x094, (word_t)format, value, 0, 0); }",
        "",
        "/* GUI API；like/candidate 语义来自原机调用形状，原始符号已丢失。 */",
        "static inline word_t system_gui_event_poll(void *message, word_t slot)",
        "{ return system_call4(g_system_api.gui, 0x030, (word_t)message, slot, 0, 0); }",
        "static inline word_t system_gui_notify(word_t object, uint32_t message, word_t wparam, word_t lparam)",
        "{ return system_call4(g_system_api.gui, 0x03c, object, message, wparam, lparam); }",
        "static inline word_t system_gui_send(word_t object, uint32_t message, word_t wparam, word_t lparam)",
        "{ return system_call4(g_system_api.gui, 0x040, object, message, wparam, lparam); }",
        "static inline word_t system_gui_frame_release(word_t frame)",
        "{ return system_call4(g_system_api.gui, 0x04c, frame, 0, 0, 0); }",
        "static inline word_t system_gui_event_step(void)",
        "{ return system_call4(g_system_api.gui, 0x050, 0, 0, 0, 0); }",
        "static inline word_t system_gui_event_dispatch(void *message)",
        "{ return system_call4(g_system_api.gui, 0x054, (word_t)message, 0, 0, 0); }",
        "static inline word_t system_gui_present(word_t enabled)",
        "{ return system_call4(g_system_api.gui, 0x074, enabled, 0, 0, 0); }",
        "static inline word_t system_gui_register_frame(void *desc)",
        "{ return system_call4(g_system_api.gui, 0x084, (word_t)desc, 0, 0, 0); }",
        "static inline word_t system_gui_frame_stop(word_t frame)",
        "{ return system_call4(g_system_api.gui, 0x088, frame, 0, 0, 0); }",
        "static inline word_t system_gui_default_proc(word_t frame, uint32_t msg, word_t wp, word_t lp)",
        "{ return system_call4(g_system_api.gui, 0x08c, frame, msg, wp, lp); }",
        "static inline word_t system_gui_object_userdata(word_t object)",
        "{ return system_call4(g_system_api.gui, 0x0b8, object, 0, 0, 0); }",
        "static inline word_t system_gui_object_op(word_t object, word_t op, word_t arg)",
        "{ return system_call4(g_system_api.gui, 0x0e0, object, op, arg, 0); }",
        "static inline word_t system_gui_object_draw_begin(word_t object)",
        "{ return system_call4(g_system_api.gui, 0x0e4, object, 0, 0, 0); }",
        "static inline word_t system_gui_object_draw_end(word_t object, word_t draw)",
        "{ return system_call4(g_system_api.gui, 0x0e8, object, draw, 0, 0); }",
        "static inline word_t system_gui_active_frame_set(word_t frame)",
        "{ return system_call4(g_system_api.gui, 0x134, frame, 0, 0, 0); }",
        "static inline word_t system_gui_close_frame(word_t frame)",
        "{ return system_call4(g_system_api.gui, 0x17c, frame, 0, 0, 0); }",
        "static inline word_t system_gui_create_window_candidate(const char *class_name,",
        "                                                        const char *title, word_t style,",
        "                                                        word_t arg3, word_t arg4, word_t arg5,",
        "                                                        word_t arg6, word_t arg7, word_t arg8,",
        "                                                        word_t parent, word_t arg10)",
        "{ return system_call11(g_system_api.gui, 0x1a4, (word_t)class_name, (word_t)title,",
        "                       style, arg3, arg4, arg5, arg6, arg7, arg8, parent, arg10); }",
        "static inline word_t system_gui_destroy(word_t object)",
        "{ return system_call4(g_system_api.gui, 0x1a8, object, 0, 0, 0); }",
        "static inline word_t system_gui_msgbox(word_t owner, const char *text, const char *title, word_t flags)",
        "{ return system_call4(g_system_api.gui, 0x2b8, owner, (word_t)text, (word_t)title, flags); }",
        "static inline word_t system_gui_draw_object_create(word_t kind)",
        "{ return system_call4(g_system_api.gui, 0x2fc, kind, 0, 0, 0); }",
        "static inline word_t system_gui_begin_draw(word_t frame)",
        "{ return system_call4(g_system_api.gui, 0x308, frame, 0, 0, 0); }",
        "static inline word_t system_gui_end_draw(word_t draw)",
        "{ return system_call4(g_system_api.gui, 0x30c, draw, 0, 0, 0); }",
        "static inline word_t system_gui_rgb(word_t draw, uint8_t red, uint8_t green, uint8_t blue)",
        "{ return system_call4(g_system_api.gui, 0x378, draw, red, green, blue); }",
        "static inline word_t system_gui_draw_vx(word_t draw, int x, int y, int width, int height,",
        "                                        const void *resource)",
        "{ return system_call8(g_system_api.gui, 0x540, draw, x, y, width, height,",
        "                      (word_t)resource, 0, 0); }",
        "static inline word_t system_gui_help_candidate(word_t frame, const char *text)",
        "{ return system_call4(g_system_api.gui, 0x5a8, frame, (word_t)text, 0, 0); }",
        "static inline word_t system_gui_draw_vx_region(word_t draw, int dst_x, int dst_y,",
        "                                                   int width, int height, const void *resource,",
        "                                                   int src_x, int src_y)",
        "{ return system_call8(g_system_api.gui, 0x5bc, draw, dst_x, dst_y, width, height,",
        "                      (word_t)resource, src_x, src_y); }",
        "static inline word_t system_gui_draw_vx_tile(word_t draw, int x, int y, int width, int height,",
        "                                                 const void *resource, word_t option0,",
        "                                                 word_t option1, word_t color)",
        "{ return system_call9(g_system_api.gui, 0x65c, draw, x, y, width, height,",
        "                      (word_t)resource, option0, option1, color); }",
        "static inline word_t system_gui_message_box_rect(uint32_t x, uint32_t y, uint32_t width,",
        "                                                     uint32_t height, word_t flags,",
        "                                                     const char *text, const char *title)",
        "{ return system_call8(g_system_api.gui, 0x690, x, y, width, height, flags,",
        "                      (word_t)text, (word_t)title, 0); }",
        "static inline word_t system_gui_mode_query_candidate(void)",
        "{ return system_call4(g_system_api.gui, 0x7c0, 0, 0, 0, 0); }",
        "static inline word_t system_delay(uint32_t ticks)",
        "{ return system_call4(g_system_api.sys, 0x080, ticks, 0, 0, 0); }",
        "",
        "#endif",
    ]
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")


def c_escape(value: str) -> str:
    return (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\r", "\\r")
        .replace("\n", "\\n")
        .replace("\t", "\\t")
    )


def short_text(value: str, limit: int = 100) -> str:
    escaped = c_escape(value)
    if len(escaped) > limit:
        return escaped[: limit - 3] + "..."
    return escaped


def name_for_va(va: int) -> str:
    return SEMANTIC_NAMES.get(va, f"sub_{va:08x}")


def emit_prelude(lines: list[str], source: str) -> None:
    lines.extend(
        [
            "/*",
            " * C-like reconstruction of BBK Element Table.",
            f" * Binary source: {source}",
            " *",
            " * This is not the original source. Names, types and structured control flow",
            " * are inferred from MIPS code, API-table calls, strings and data xrefs.",
            " * It is syntax-checkable documentation, not a drop-in rebuild of the BDA.",
            " */",
            "",
            "#include <stddef.h>",
            "#include <stdint.h>",
            "#include <stdarg.h>",
            "#include \"system.h\"",
            "",
            "typedef word_t FileHandle;",
            "typedef word_t WindowHandle;",
            "typedef word_t DrawHandle;",
            "",
            "typedef struct AppDlxTable AppDlxTable;",
            "typedef word_t (*WindowProc)(WindowHandle, uint32_t, word_t, word_t);",
            "typedef int (*LocalFormatEmit)(int ch, void *context);",
            "typedef struct LocalHeapBlock {",
            "    uintptr_t address;",
            "    uint32_t size_flags;  /* bit 0: allocated */",
            "} LocalHeapBlock;",
            "typedef struct LocalStreamLike {",
            "    uint16_t mode;",
            "    uint8_t state;",
            "    uint8_t reserved;",
            "    uint32_t value;",
            "} LocalStreamLike;",
            "",
            "typedef struct BootApiTables {",
            "    word_t reserved_00;",
            "    ApiTable *gui;       /* image VA 0x81c00004 */",
            "    ApiTable *fs;        /* image VA 0x81c00008 */",
            "    ApiTable *sys;       /* image VA 0x81c0000c */",
            "    ApiTable *mem;       /* image VA 0x81c00010 */",
            "    ApiTable *res;       /* image VA 0x81c00014 */",
            "} BootApiTables;",
            "",
            "#pragma pack(push, 1)",
            "typedef struct DlxHeader {",
            "    uint8_t magic[3];       /* 'D', 'L', 'X' */",
            "    uint8_t resource_count;",
            "    uint8_t format_flag;",
            "    uint8_t variant;",
            "    uint16_t reserved_06;",
            "    uint32_t signature;     /* 0x19811108 */",
            "    uint32_t header_size;   /* first resource file offset */",
            "    uint32_t payload_size;  /* bytes following this 0x24-byte header */",
            "    char producer[16];",
            "} DlxHeader;",
            "",
            "typedef struct DlxEntry {",
            "    uint32_t type;",
            "    uint32_t offset;",
            "    uint32_t size;",
            "} DlxEntry;",
            "",
            "struct AppDlxTable {",
            "    uint8_t count;",
            "    uint8_t reserved[3];",
            "    DlxEntry entries[];     /* entries[count], then raw resource payload */",
            "};",
            "",
            "typedef struct LoadedDlxResource {",
            "    uint8_t status;         /* 0=ok, 1=open, 2=header, 3=alloc */",
            "    uint8_t reserved[3];",
            "    uint32_t type;",
            "    uint32_t size;",
            "    void *data;",
            "} LoadedDlxResource;",
            "#pragma pack(pop)",
            "",
            "#if UINTPTR_MAX == 0xffffffffu",
            "_Static_assert(sizeof(DlxHeader) == 0x24, \"DLX header layout\");",
            "_Static_assert(sizeof(DlxEntry) == 0x0c, \"DLX entry layout\");",
            "_Static_assert(sizeof(LoadedDlxResource) == 0x10, \"loaded resource layout\");",
            "#endif",
            "",
            "typedef struct WindowDescLike {",
            "    uint32_t style;       /* +0x00 */",
            "    word_t reserved_04;   /* +0x04 */",
            "    const char *title;    /* +0x08 on the 32-bit target */",
            "    word_t reserved_0c;",
            "    word_t reserved_10;",
            "    word_t reserved_14;",
            "    WindowProc proc;      /* +0x18 on the 32-bit target */",
            "    word_t reserved_1c;",
            "    word_t reserved_20;",
            "    uint32_t height;      /* +0x24 */",
            "    uint32_t width;       /* +0x28 */",
            "    word_t surface;       /* +0x2c */",
            "    word_t reserved_30;",
            "    word_t reserved_34;",
            "} WindowDescLike;",
            "",
            "/* Recovered BSS/global locations. */",
            "SystemApiContext g_system_api;",
            "static ApiTable *g_res;                /* 0x81c04480 */",
            "static ApiTable *g_gui;                /* 0x81c04484 */",
            "static ApiTable *g_sys;                /* 0x81c04488 */",
            "static ApiTable *g_fs;                 /* 0x81c0448c */",
            "static ApiTable *g_mem;                /* 0x81c04490 */",
            "static WindowHandle g_element_frame;   /* 0x81c04494 */",
            "static WindowHandle g_periodic_frame;  /* 0x81c04498 */",
            "static word_t g_dict_view;             /* 0x81c0449c */",
            "static FileHandle g_data_file;         /* 0x81c044a0 */",
            "static uint32_t g_using_fallback_dlx;  /* 0x81c044d0 */",
            "static uint32_t g_hx_offsets[116];     /* 0x81c044d4..0x81c046a0 */",
            "static char g_hx_scratch[0x1fa0];      /* 0x81c046a4.. */",
            "static AppDlxTable *g_dlx_table;       /* 0x81c06644 */",
            "static void *g_current_resource;       /* 0x81c06648 */",
            "static DrawHandle g_current_draw;      /* 0x81c0664c */",
            "static uint8_t g_offset24[3];          /* 0x81c06650 */",
            "static uint32_t g_selected_element = 1;/* image VA 0x81c04378 */",
            "static uintptr_t g_heap_start;          /* reconstructed $gp+0x40 */",
            "static uintptr_t g_heap_end;            /* reconstructed $gp+0x3c */",
            "static uintptr_t g_heap_cursor;         /* reconstructed $gp+0x4c */",
            "static uintptr_t g_heap_limit;          /* reconstructed $gp+0x44 */",
            "static word_t g_heap_free_list;         /* reconstructed $gp+0x48 */",
            "static LocalHeapBlock g_heap_blocks[128];",
            "static size_t g_heap_block_count;",
            "static int g_local_errno;               /* image VA 0x81c044a4 */",
            "static LocalStreamLike g_local_streams[3]; /* image VA 0x81c06680 */",
            "",
        ]
    )


def emit_strings(lines: list[str], strings: list[dict]) -> None:
    lines.append("/* Recovered high-confidence strings, named by BDA file offset. */")
    seen: set[int] = set()
    for item in strings:
        off = int(item["file_offset"])
        if off in seen:
            continue
        seen.add(off)
        lines.append(
            f'static const char str_{off:08x}[] = "{c_escape(item["text"])}";'
        )
    lines.append("")


def emit_prototypes(lines: list[str], functions: list[dict]) -> None:
    lines.extend(
        [
            "int element_table_entry(void);",
            "static void runtime_bootstrap(void);",
            "static AppDlxTable *load_dlx_resource_file(const char *path);",
            "static int load_dlx_resource_by_index(const char *path, uint16_t resource_number, LoadedDlxResource *out);",
            "static void *get_dlx_resource(uint32_t resource_number, AppDlxTable *table);",
            "static void free_loaded_dlx_resource_payload(LoadedDlxResource *resource);",
            "static void free_dlx_resource_table(AppDlxTable *table);",
            "static word_t element_detail_window_proc(WindowHandle frame, uint32_t msg, word_t wparam, word_t lparam);",
            "static word_t periodic_table_window_proc(WindowHandle frame, uint32_t msg, word_t wparam, word_t lparam);",
            "static int element_table_main(void);",
            "static void load_hx_offset_table(void);",
            "static void load_element_description(uint32_t index);",
            "static WindowHandle run_standard_window(WindowProc proc);",
            "static void resource_noop(void);",
            "static void *local_memchr(const void *buffer, int value, size_t count);",
            "static size_t local_strlen(const char *text);",
            "static int local_sprintf(char *dst, const char *format, ...);",
            "static int local_vsprintf(char *dst, const char *format, va_list args);",
            "static int local_format_core(const char *format, va_list args, LocalFormatEmit emit, void *context);",
            "static long local_strtol(const char *text, char **endptr, int base);",
            "static int local_atoi(const char *text);",
            "static void *local_memset(void *buffer, int value, size_t count);",
            "static int local_isdigit(int ch);",
            "static int local_isspace(int ch);",
            "static int local_toupper(int ch);",
            "static int local_heap_init(void *start, void *end);",
            "static void local_shift_pairs_back(uint32_t *pairs, int count);",
            "static void local_crt_init(void);",
            "static void *local_malloc(size_t size);",
            "static void *local_malloc_zero_probe(void);",
            "static void draw_current_element_tile(void);",
            "static void draw_current_element_highlight(void);",
            "static void draw_periodic_table(WindowHandle frame);",
            "static void draw_element_detail(WindowHandle frame);",
            "static void initialize_element_detail(WindowHandle frame);",
            "static uint32_t hit_test_periodic_table(uint32_t x, uint32_t y);",
            "static void open_element_detail(WindowHandle parent);",
            "static void flash_screen_button(WindowHandle frame, int x, int y, int width, int height);",
        ]
    )
    special = {
        0x81C00020, 0x81C00050, 0x81C001A0, 0x81C002F8, 0x81C004BC,
        0x81C00648, 0x81C00654, 0x81C0069C, 0x81C00F7C, 0x81C01204,
        0x81C027D0, 0x81C02854,
        0x81C0280C, 0x81C02884, 0x81C02AD8, 0x81C02AF8, 0x81C02B60,
        0x81C02BD0, 0x81C03480, 0x81C034A0,
        0x81C03320, 0x81C034D0, 0x81C034F0, 0x81C03668, 0x81C036B8,
        0x81C036E0,
        0x81C006D0, 0x81C014DC, 0x81C0218C, 0x81C0240C, 0x81C02598,
        0x81C026C0,
    }
    for function in functions:
        va = int(function["va"])
        if va not in special and not name_for_va(va).endswith("_block"):
            lines.append(f"static word_t {name_for_va(va)}(void);")
    lines.append("")


def emit_semantic_core(lines: list[str], navigation_pairs: list[tuple[int, int]]) -> None:
    lines.append("/* 原映像 0x81c03fb8 的上下邻接导航表；索引即元素原子序数。 */")
    lines.append("static const uint32_t k_element_neighbors[119][2] = {")
    for index in range(0, len(navigation_pairs), 6):
        chunk = navigation_pairs[index:index + 6]
        values = ", ".join(f"{{{up}, {down}}}" for up, down in chunk)
        lines.append(f"    {values},")
    lines.extend(["};", ""])
    lines.extend(
        [
            "/* BDA 入口：初始化接口表后进入应用主函数。 */",
            "__attribute__((section(\".text.bda_main\")))",
            "int bda_main(void)",
            "{",
            "    return element_table_entry();",
            "}",
            "",
            "int element_table_entry(void) /* 0x81c00020 */",
            "{",
            "    runtime_bootstrap();",
            "    return element_table_main();",
            "}",
            "",
            "/* 清零 BSS，缓存五张系统 API 表，并输出各表地址。 */",
            "static void runtime_bootstrap(void) /* 0x81c00050 */",
            "{",
            "    BootApiTables *boot = (BootApiTables *)(uintptr_t)0x81c00000u;",
            "",
            "    /* Original code first clears 0x81c04480..0x81c06731. */",
            "    g_gui = boot->gui;",
            "    g_fs  = boot->fs;",
            "    g_sys = boot->sys;",
            "    g_mem = boot->mem;",
            "    g_res = boot->res;",
            "    g_system_api.res = g_res;",
            "    g_system_api.gui = g_gui;",
            "    g_system_api.sys = g_sys;",
            "    g_system_api.fs = g_fs;",
            "    g_system_api.mem = g_mem;",
            "",
            "    system_res_trace(str_0000cd48, (word_t)boot);",
            "    system_res_trace(str_0000cd64, (word_t)g_gui);",
            "    system_res_trace(str_0000cd84, (word_t)g_fs);",
            "    system_res_trace(str_0000cda4, (word_t)g_sys);",
            "    system_res_trace(str_0000cdc8, (word_t)g_mem);",
            "    system_res_trace(str_0000cdec, (word_t)g_res);",
            "}",
            "",
            "/* 打开并解析 DLX 文件，返回应用私有资源表。 */",
            "static AppDlxTable *load_dlx_resource_file(const char *path) /* 0x81c001a0 */",
            "{",
            "    DlxHeader header;",
            "    FileHandle file = system_fs_open(path, \"rb\");",
            "    AppDlxTable *table;",
            "",
            "    if (!file)",
            "        return NULL;",
            "    (void)system_fs_read(&header, sizeof(header), 1, file);",
            "",
            "    if (header.magic[0] != 'D' || header.magic[1] != 'L' || header.magic[2] != 'X' ||",
            "        (header.format_flag == 0 && header.variant < 3) ||",
            "        header.signature != 0x19811108u) {",
            "        /* 原始 0x81c00240 路径直接返回，未调用 FS_CLOSE。 */",
            "        return NULL;",
            "    }",
            "",
            "    table = (AppDlxTable *)system_mem_alloc((size_t)header.payload_size + 8u);",
            "    if (!table) {",
            "        system_fs_close(file);",
            "        return NULL;",
            "    }",
            "    table->count = header.resource_count;",
            "",
            "    if (system_fs_read((uint8_t *)table + 4, header.payload_size, 1, file)) {",
            "        system_fs_close(file);",
            "        return table;",
            "    }",
            "",
            "    system_mem_free(table);",
            "    /* 原始读取失败路径同样没有关闭 file；这里保留该行为。 */",
            "    return NULL;",
            "}",
            "",
            "/* 从 DLX 中按 1 基索引加载一个资源。返回值与 out->status 相同。 */",
            "static int load_dlx_resource_by_index(const char *path, uint16_t resource_number,",
            "                                      LoadedDlxResource *out) /* 0x81c002f8 */",
            "{",
            "    DlxHeader header;",
            "    DlxEntry entry = {0};",
            "    FileHandle file;",
            "    uint16_t i;",
            "",
            "    file = system_fs_open(path, \"rb\");",
            "    if (!file) {",
            "        out->status = 1;",
            "        return 1;",
            "    }",
            "",
            "    (void)system_fs_read(&header, sizeof(header), 1, file);",
            "    if (header.magic[0] != 'D' || header.magic[1] != 'L' || header.magic[2] != 'X' ||",
            "        header.signature != 0x19811108u) {",
            "        out->status = 2;",
            "        /* 原始无效头路径不关闭文件。 */",
            "        return 2;",
            "    }",
            "",
            "    /* 原程序循环 resource_number 次，因此第一个资源编号为 1。 */",
            "    for (i = 0; i < resource_number; ++i)",
            "        (void)system_fs_read(&entry, sizeof(entry), 1, file);",
            "",
            "    out->type = entry.type;",
            "    out->size = entry.size;",
            "    system_fs_seek(file, header.header_size + entry.offset, 0);",
            "    out->data = system_mem_alloc((size_t)entry.size + 1u);",
            "    if (!out->data) {",
            "        system_fs_close(file);",
            "        out->status = 3;",
            "        return 3;",
            "    }",
            "",
            "    (void)system_fs_read(out->data, 1, entry.size, file);",
            "    system_fs_close(file);",
            "    out->status = 0;",
            "    return 0;",
            "}",
            "",
            "/* 按索引取得带 VX 头的完整资源块。 */",
            "static void *get_dlx_resource(uint32_t resource_number, AppDlxTable *table) /* 0x81c004bc */",
            "{",
            "    uint8_t *payload_base;",
            "    DlxEntry *entry;",
            "",
            "    if (!table || resource_number == 0 || resource_number > table->count)",
            "        return NULL;",
            "    payload_base = (uint8_t *)&table->entries[table->count];",
            "    entry = &table->entries[resource_number - 1];",
            "    return payload_base + entry->offset;",
            "}",
            "",
            "/* 释放单资源加载结果中的数据，但保留状态、类型和大小。 */",
            "static void free_loaded_dlx_resource_payload(LoadedDlxResource *resource) /* 0x81c00654 */",
            "{",
            "    if (resource->data) {",
            "        system_mem_free(resource->data);",
            "        resource->data = NULL;",
            "    }",
            "}",
            "",
            "/* 释放应用私有 DLX 资源表。 */",
            "static void free_dlx_resource_table(AppDlxTable *table) /* 0x81c0069c */",
            "{",
            "    if (table)",
            "        system_mem_free(table);",
            "}",
            "",
            "/* 从 HX 文件读取 114 个 24 位正文偏移。 */",
            "static void load_hx_offset_table(void) /* 0x81c0240c */",
            "{",
            "    uint32_t i, relative;",
            "    FileHandle file;",
            "",
            "    /* 原程序只清零起始 0x74 字节，而不是整个偏移数组。 */",
            "    local_memset(g_hx_offsets, 0, 0x74);",
            "    file = system_fs_open(str_0000d1cc, \"rb\");",
            "    if (!file) {",
            "        system_res_trace(str_0000d1f0, 0);",
            "        return;",
            "    }",
            "",
            "    system_fs_seek(file, 0x24, 0);",
            "    (void)system_fs_read(&g_hx_offsets[0], 3, 1, file);",
            "    system_res_trace(str_0000d278, g_hx_offsets[0]);",
            "",
            "    /* 0x2a1b9 处保存 114 个小端 24 位相对偏移。 */",
            "    system_fs_seek(file, 0x0002a1b9u, 0);",
            "    for (i = 0; i < 114; ++i) {",
            "        (void)system_fs_read(g_offset24, 3, 1, file);",
            "        relative = (uint32_t)g_offset24[0]",
            "                 | ((uint32_t)g_offset24[1] << 8)",
            "                 | ((uint32_t)g_offset24[2] << 16);",
            "        g_hx_offsets[i + 1] = g_hx_offsets[0] + relative;",
            "    }",
            "    g_hx_offsets[115] = 0x0002a071u;",
            "    system_fs_close(file);",
            "}",
            "",
            "/* 按元素编号读取正文到共享缓冲区。 */",
            "static void load_element_description(uint32_t index) /* 0x81c02598 */",
            "{",
            "    uint32_t start, size;",
            "    FileHandle file;",
            "",
            "    if (index == 0 || index >= 115)",
            "        return;",
            "    local_memset(g_hx_scratch, 0, sizeof(g_hx_scratch));",
            "",
            "    start = g_hx_offsets[index];",
            "    size = g_hx_offsets[index + 1] - start;",
            "    file = system_fs_open(str_0000d1cc, \"rb\");",
            "    g_data_file = file;",
            "    if (!file) {",
            "        system_res_trace(str_0000d1f0, 0);",
            "        return;",
            "    }",
            "    system_fs_seek(file, start, 0);",
            "    (void)system_fs_read(g_hx_scratch, size, 1, file);",
            "    system_fs_close(file);",
            "    system_res_trace(str_0000d23c, local_strlen(g_hx_scratch));",
            "}",
            "",
            "/* 本地 strlen，逐字节扫描 NUL。 */",
            "static size_t local_strlen(const char *text) /* 0x81c02854 */",
            "{",
            "    const char *cursor = text;",
            "    while (*cursor)",
            "        ++cursor;",
            "    return (size_t)(cursor - text);",
            "}",
            "",
            "/* 原地址只建立栈帧后立即返回。 */",
            "static void resource_noop(void) /* 0x81c00648 */",
            "{",
            "}",
            "",
            "/* 本地 memchr：最多检查 count 个字节。 */",
            "static void *local_memchr(const void *buffer, int value, size_t count) /* 0x81c027d0 */",
            "{",
            "    const uint8_t *cursor = (const uint8_t *)buffer;",
            "    uint8_t wanted = (uint8_t)value;",
            "    while (count--) {",
            "        if (*cursor == wanted)",
            "            return (void *)cursor;",
            "        ++cursor;",
            "    }",
            "    return NULL;",
            "}",
            "",
            "/* 本地字符分类函数返回原字符或零，与标准 ctype 的布尔值略有不同。 */",
            "static int local_isdigit(int ch) /* 0x81c03480 */",
            "{",
            "    int8_t c = (int8_t)ch;",
            "    return (c >= '0' && c <= '9') ? c : 0;",
            "}",
            "",
            "static int local_isspace(int ch) /* 0x81c034a0 */",
            "{",
            "    int8_t c = (int8_t)ch;",
            "    return (c == ' ' || (c >= '\\t' && c <= '\\r')) ? c : 0;",
            "}",
            "",
            "static int local_toupper(int ch) /* 0x81c034d0 */",
            "{",
            "    int8_t c = (int8_t)ch;",
            "    return (c >= 'a' && c <= 'z') ? c - 0x20 : c;",
            "}",
            "",
            "static void *local_memset(void *buffer, int value, size_t count) /* 0x81c02b60 */",
            "{",
            "    uint8_t *cursor = (uint8_t *)buffer;",
            "    while (count--)",
            "        *cursor++ = (uint8_t)value;",
            "    return buffer;",
            "}",
            "",
            "/* GCC 可在 freestanding 优化中生成 memset 调用，导出本地实现供链接器使用。 */",
            "void *memset(void *buffer, int value, size_t count)",
            "{",
            "    return local_memset(buffer, value, count);",
            "}",
            "",
            "/* 本地 strtol：控制流按 0x81c02884 重建，未恢复 errno/溢出报告。 */",
            "static long local_strtol(const char *text, char **endptr, int base) /* 0x81c02884 */",
            "{",
            "    const char *cursor = text;",
            "    const char *digits_begin;",
            "    unsigned long value = 0;",
            "    int negative = 0;",
            "",
            "    while (local_isspace((uint8_t)*cursor))",
            "        ++cursor;",
            "    if (*cursor == '+' || *cursor == '-') {",
            "        negative = (*cursor == '-');",
            "        ++cursor;",
            "    }",
            "    if ((base == 0 || base == 16) && cursor[0] == '0' &&",
            "        (cursor[1] == 'x' || cursor[1] == 'X')) {",
            "        base = 16;",
            "        cursor += 2;",
            "    } else if (base == 0) {",
            "        base = (*cursor == '0') ? 8 : 10;",
            "    }",
            "    if (base < 2 || base > 36) {",
            "        if (endptr)",
            "            *endptr = (char *)text;",
            "        return 0;",
            "    }",
            "",
            "    digits_begin = cursor;",
            "    for (;;) {",
            "        int ch = (uint8_t)*cursor;",
            "        int digit;",
            "        if (ch >= '0' && ch <= '9')",
            "            digit = ch - '0';",
            "        else if (ch >= 'a' && ch <= 'z')",
            "            digit = ch - 'a' + 10;",
            "        else if (ch >= 'A' && ch <= 'Z')",
            "            digit = ch - 'A' + 10;",
            "        else",
            "            break;",
            "        if (digit >= base)",
            "            break;",
            "        value = value * (unsigned)base + (unsigned)digit;",
            "        ++cursor;",
            "    }",
            "    if (endptr)",
            "        *endptr = (char *)(cursor == digits_begin ? text : cursor);",
            "    return negative ? -(long)value : (long)value;",
            "}",
            "",
            "static int local_atoi(const char *text) /* 0x81c02ad8 */",
            "{",
            "    return (int)local_strtol(text, NULL, 10);",
            "}",
            "",
            "static int local_buffer_emit(int ch, void *context)",
            "{",
            "    char **cursor = (char **)context;",
            "    *(*cursor)++ = (char)ch;",
            "    return ch;",
            "}",
            "",
            "static void local_format_emit_char(LocalFormatEmit emit, void *context,",
            "                                   int ch, int *count)",
            "{",
            "    emit(ch, context);",
            "    ++*count;",
            "}",
            "",
            "static void local_format_emit_repeat(LocalFormatEmit emit, void *context,",
            "                                     int ch, int amount, int *count)",
            "{",
            "    while (amount-- > 0)",
            "        local_format_emit_char(emit, context, ch, count);",
            "}",
            "",
            "static int local_format_u32(char *digits, uint32_t value, unsigned base, int uppercase)",
            "{",
            "    const char *alphabet = uppercase ? \"0123456789ABCDEF\" : \"0123456789abcdef\";",
            "    char reverse[32];",
            "    int length = 0, i;",
            "    do {",
            "        reverse[length++] = alphabet[value % base];",
            "        value /= base;",
            "    } while (value != 0);",
            "    for (i = 0; i < length; ++i)",
            "        digits[i] = reverse[length - i - 1];",
            "    return length;",
            "}",
            "",
            "/*",
            " * printf/sprintf 共用的 freestanding 格式化核心。",
            " * 支持原函数控制流中出现的 flags、宽度、精度、h/l、整数、字符串、",
            " * 字符、指针、%n 和 %%；通过回调逐字符输出，不依赖 libc。",
            " */",
            "static int local_format_core(const char *format, va_list args, LocalFormatEmit emit,",
            "                             void *context) /* 0x81c02bd0 */",
            "{",
            "    int count = 0;",
            "",
            "    while (*format) {",
            "        int left = 0, plus = 0, space = 0, alternate = 0, zero = 0;",
            "        int width = 0, precision = -1, short_arg = 0, long_arg = 0;",
            "        int spec;",
            "",
            "        if (*format != '%') {",
            "            local_format_emit_char(emit, context, (uint8_t)*format++, &count);",
            "            continue;",
            "        }",
            "        ++format;",
            "        for (;;) {",
            "            if (*format == '-') left = 1;",
            "            else if (*format == '+') plus = 1;",
            "            else if (*format == ' ') space = 1;",
            "            else if (*format == '#') alternate = 1;",
            "            else if (*format == '0') zero = 1;",
            "            else break;",
            "            ++format;",
            "        }",
            "",
            "        if (*format == '*') {",
            "            width = va_arg(args, int);",
            "            ++format;",
            "            if (width < 0) { left = 1; width = -width; }",
            "        } else {",
            "            while (*format >= '0' && *format <= '9')",
            "                width = width * 10 + (*format++ - '0');",
            "        }",
            "        if (*format == '.') {",
            "            ++format;",
            "            precision = 0;",
            "            if (*format == '*') {",
            "                precision = va_arg(args, int);",
            "                ++format;",
            "                if (precision < 0) precision = -1;",
            "            } else {",
            "                while (*format >= '0' && *format <= '9')",
            "                    precision = precision * 10 + (*format++ - '0');",
            "            }",
            "        }",
            "        if (*format == 'h') { short_arg = 1; ++format; }",
            "        else if (*format == 'l') { long_arg = 1; ++format; }",
            "",
            "        spec = (uint8_t)*format;",
            "        if (spec)",
            "            ++format;",
            "        if (spec == '%') {",
            "            local_format_emit_char(emit, context, '%', &count);",
            "            continue;",
            "        }",
            "        if (spec == 'n') {",
            "            if (short_arg) *va_arg(args, short *) = (short)count;",
            "            else if (long_arg) *va_arg(args, long *) = (long)count;",
            "            else *va_arg(args, int *) = count;",
            "            continue;",
            "        }",
            "        if (spec == 'c') {",
            "            int padding = width > 1 ? width - 1 : 0;",
            "            if (!left) local_format_emit_repeat(emit, context, ' ', padding, &count);",
            "            local_format_emit_char(emit, context, va_arg(args, int), &count);",
            "            if (left) local_format_emit_repeat(emit, context, ' ', padding, &count);",
            "            continue;",
            "        }",
            "        if (spec == 's') {",
            "            const char *text = va_arg(args, const char *);",
            "            int length, padding, i;",
            "            if (!text) text = \"(null)\";",
            "            length = (int)local_strlen(text);",
            "            if (precision >= 0 && length > precision) length = precision;",
            "            padding = width > length ? width - length : 0;",
            "            if (!left) local_format_emit_repeat(emit, context, ' ', padding, &count);",
            "            for (i = 0; i < length; ++i)",
            "                local_format_emit_char(emit, context, (uint8_t)text[i], &count);",
            "            if (left) local_format_emit_repeat(emit, context, ' ', padding, &count);",
            "            continue;",
            "        }",
            "",
            "        if (spec == 'd' || spec == 'i' || spec == 'u' || spec == 'o' ||",
            "            spec == 'x' || spec == 'X' || spec == 'p') {",
            "            char digits[32];",
            "            char prefix[2];",
            "            uint32_t value;",
            "            unsigned base = 10;",
            "            int uppercase = spec == 'X';",
            "            int prefix_length = 0, digit_length, zeroes, padding, i;",
            "",
            "            if (spec == 'd' || spec == 'i') {",
            "                int32_t signed_value = (int32_t)va_arg(args, int);",
            "                if (short_arg) signed_value = (int16_t)signed_value;",
            "                if (signed_value < 0) {",
            "                    prefix[prefix_length++] = '-';",
            "                    value = 0u - (uint32_t)signed_value;",
            "                } else {",
            "                    value = (uint32_t)signed_value;",
            "                    if (plus) prefix[prefix_length++] = '+';",
            "                    else if (space) prefix[prefix_length++] = ' ';",
            "                }",
            "            } else if (spec == 'p') {",
            "                value = (uint32_t)(uintptr_t)va_arg(args, void *);",
            "                base = 16;",
            "                prefix[prefix_length++] = '0';",
            "                prefix[prefix_length++] = 'x';",
            "                if (precision < 0) precision = 8;",
            "            } else {",
            "                value = va_arg(args, uint32_t);",
            "                if (short_arg) value = (uint16_t)value;",
            "                if (spec == 'o') base = 8;",
            "                else if (spec == 'x' || spec == 'X') base = 16;",
            "                if (alternate && value != 0 && base == 8)",
            "                    prefix[prefix_length++] = '0';",
            "                else if (alternate && value != 0 && base == 16) {",
            "                    prefix[prefix_length++] = '0';",
            "                    prefix[prefix_length++] = uppercase ? 'X' : 'x';",
            "                }",
            "            }",
            "",
            "            digit_length = local_format_u32(digits, value, base, uppercase);",
            "            if (precision == 0 && value == 0) digit_length = 0;",
            "            zeroes = precision > digit_length ? precision - digit_length : 0;",
            "            padding = width - prefix_length - zeroes - digit_length;",
            "            if (padding < 0) padding = 0;",
            "            if (!left && !(zero && precision < 0))",
            "                local_format_emit_repeat(emit, context, ' ', padding, &count);",
            "            for (i = 0; i < prefix_length; ++i)",
            "                local_format_emit_char(emit, context, prefix[i], &count);",
            "            if (!left && zero && precision < 0)",
            "                local_format_emit_repeat(emit, context, '0', padding, &count);",
            "            local_format_emit_repeat(emit, context, '0', zeroes, &count);",
            "            for (i = 0; i < digit_length; ++i)",
            "                local_format_emit_char(emit, context, digits[i], &count);",
            "            if (left) local_format_emit_repeat(emit, context, ' ', padding, &count);",
            "            continue;",
            "        }",
            "",
            "        /* 未知格式按原样输出，避免静默丢失。 */",
            "        local_format_emit_char(emit, context, '%', &count);",
            "        if (spec)",
            "            local_format_emit_char(emit, context, spec, &count);",
            "    }",
            "    return count;",
            "}",
            "",
            "static int local_vsprintf(char *dst, const char *format, va_list args) /* 0x81c02af8 */",
            "{",
            "    char *cursor = dst;",
            "    int result = local_format_core(format, args, local_buffer_emit, &cursor);",
            "    *cursor = '\\0';",
            "    return result;",
            "}",
            "",
            "static int local_sprintf(char *dst, const char *format, ...) /* 0x81c0280c */",
            "{",
            "    va_list args;",
            "    int result;",
            "    va_start(args, format);",
            "    result = local_vsprintf(dst, format, args);",
            "    va_end(args);",
            "    return result;",
            "}",
            "",
            "/* 初始化应用内置小型堆；地址按 4 字节对齐。 */",
            "static int local_heap_init(void *start, void *end) /* 0x81c03668 */",
            "{",
            "    uintptr_t aligned_start = ((uintptr_t)start + 3u) & ~(uintptr_t)3u;",
            "    uintptr_t aligned_end = ((uintptr_t)end + 3u) & ~(uintptr_t)3u;",
            "    g_heap_start = aligned_start;",
            "    g_heap_end = aligned_end;",
            "    if (aligned_end < aligned_start + 0x10u)",
            "        return 1;",
            "    g_heap_cursor = aligned_start;",
            "    g_heap_limit = aligned_end - 8u;",
            "    g_heap_free_list = 0;",
            "    g_heap_block_count = 0;",
            "    return 0;",
            "}",
            "",
            "/* memmove(pairs - 2, pairs, count * 8) 的定长描述符版本。 */",
            "static void local_shift_pairs_back(uint32_t *pairs, int count) /* 0x81c036e0 */",
            "{",
            "    int i;",
            "    for (i = 0; i < count; ++i) {",
            "        pairs[-2] = pairs[0];",
            "        pairs[-1] = pairs[1];",
            "        pairs += 2;",
            "    }",
            "}",
            "",
            "/* 初始化三项本地流状态和 0x80a32000..0x81c00000 内置堆。 */",
            "static void local_crt_init(void) /* 0x81c03320 */",
            "{",
            "    size_t i;",
            "    for (i = 0; i < 3; ++i) {",
            "        g_local_streams[i].mode = 0x45;",
            "        g_local_streams[i].state = 0;",
            "        g_local_streams[i].reserved = 0;",
            "        g_local_streams[i].value = (i == 1) ? 1u : (i == 2 ? 2u : 0u);",
            "    }",
            "    g_local_errno = 0;",
            "    (void)local_heap_init((void *)(uintptr_t)0x80a32000u,",
            "                          (void *)(uintptr_t)0x81c00000u);",
            "}",
            "",
            "/* 内置堆的高层重建：4 字节对齐，描述符单独记录并支持复用空闲块。 */",
            "static void *local_malloc(size_t size) /* 0x81c034f0 */",
            "{",
            "    size_t i;",
            "    uint32_t aligned;",
            "    uintptr_t result;",
            "    if (size == 0)",
            "        return NULL;",
            "    aligned = ((uint32_t)size + 3u) & ~3u;",
            "",
            "    for (i = 0; i < g_heap_block_count; ++i) {",
            "        uint32_t block_size = g_heap_blocks[i].size_flags & ~1u;",
            "        if (!(g_heap_blocks[i].size_flags & 1u) && block_size >= aligned) {",
            "            g_heap_blocks[i].size_flags = block_size | 1u;",
            "            return (void *)g_heap_blocks[i].address;",
            "        }",
            "    }",
            "",
            "    if (g_heap_block_count >= 128 || g_heap_limit < g_heap_cursor ||",
            "        g_heap_limit - g_heap_cursor < (uintptr_t)aligned + 8u) {",
            "        g_local_errno = 12;",
            "        return NULL;",
            "    }",
            "    result = g_heap_cursor;",
            "    g_heap_blocks[g_heap_block_count].address = result;",
            "    g_heap_blocks[g_heap_block_count].size_flags = aligned | 1u;",
            "    ++g_heap_block_count;",
            "    g_heap_cursor += aligned;",
            "    g_heap_limit -= 8u;",
            "    return (void *)result;",
            "}",
            "",
            "static void *local_malloc_zero_probe(void) /* 0x81c036b8 */",
            "{",
            "    return local_malloc(0);",
            "}",
            "",
            "/* 创建标准窗口并运行消息循环。 */",
            "static WindowHandle run_standard_window(WindowProc proc) /* 0x81c026c0 */",
            "{",
            "    WindowDescLike desc = {0};",
            "    word_t message[8] = {0};",
            "    WindowHandle frame;",
            "    desc.style = 0x08000000u;",
            "    desc.title = \"\";",
            "    desc.proc = proc;",
            "    desc.height = 240;",
            "    desc.width = 320;",
            "    desc.surface = system_gui_draw_object_create(15);",
            "    frame = system_gui_register_frame(&desc);",
            "    if (frame == (WindowHandle)-1)",
            "        return 0;",
            "    while (system_gui_event_poll(message, 0)) {",
            "        system_gui_event_step();",
            "        system_gui_event_dispatch(message);",
            "    }",
            "    system_gui_close_frame(frame);",
            "    return frame;",
            "}",
            "",
            "static void element_tile_position(uint32_t n, int *x, int *y)",
            "{",
            "    if (n < 3)       { *x = 221 * (int)n - 220; *y = 162; }",
            "    else if (n < 5)  { *x = 13 * (int)n - 38;   *y = 175; }",
            "    else if (n < 11) { *x = 13 * (int)n + 92;   *y = 175; }",
            "    else if (n < 13) { *x = 13 * (int)n - 142;  *y = 188; }",
            "    else if (n < 19) { *x = 13 * (int)n - 12;   *y = 188; }",
            "    else if (n < 37) { *x = 13 * (int)n - 246;  *y = 201; }",
            "    else if (n < 55) { *x = 13 * (int)n - 480;  *y = 214; }",
            "    else if (n < 57) { *x = 13 * (int)n - 714;  *y = 227; }",
            "    else if (n < 72) { *x = 13 * (int)n - 701;  *y = 258; }",
            "    else if (n < 87) { *x = 13 * (int)n - 896;  *y = 227; }",
            "    else if (n < 89) { *x = 13 * (int)n - 1130; *y = 240; }",
            "    else if (n < 104){ *x = 13 * (int)n - 1117; *y = 271; }",
            "    else             { *x = 13 * (int)n - 1312; *y = 240; }",
            "}",
            "",
            "static void element_atlas_position(uint32_t n, int *x, int *y)",
            "{",
            "    if (n < 3)       { *x = 714 * ((int)n - 1); *y = 0; }",
            "    else if (n < 5)  { *x = 42 * (int)n - 126;  *y = 39; }",
            "    else if (n < 11) { *x = 42 * (int)n + 294;  *y = 39; }",
            "    else if (n < 13) { *x = 42 * (int)n - 462;  *y = 78; }",
            "    else if (n < 19) { *x = 42 * (int)n - 42;   *y = 78; }",
            "    else if (n < 37) { *x = 42 * (int)n - 798;  *y = 117; }",
            "    else if (n < 55) { *x = 42 * (int)n - 1554; *y = 156; }",
            "    else if (n < 57) { *x = 42 * (int)n - 2310; *y = 195; }",
            "    else if (n < 72) { *x = 42 * (int)n - 2310; *y = 304; }",
            "    else if (n < 87) { *x = 42 * (int)n - 2898; *y = 195; }",
            "    else if (n < 89) { *x = 42 * (int)n - 3654; *y = 234; }",
            "    else if (n < 104){ *x = 42 * (int)n - 3654; *y = 343; }",
            "    else             { *x = 42 * (int)n - 4242; *y = 234; }",
            "}",
            "",
            "/* 从资源 4 的 16x16 图集中绘制当前元素标记。 */",
            "static void draw_current_element_tile(void) /* 0x81c00f7c */",
            "{",
            "    int x, y;",
            "    word_t color;",
            "    void *resource = get_dlx_resource(4, g_dlx_table);",
            "    if (!resource)",
            "        return;",
            "    element_tile_position(g_selected_element, &x, &y);",
            "    color = system_gui_rgb(g_current_draw, 255, 0, 255);",
            "    system_gui_draw_vx_tile(g_current_draw, x, y, 16, 16, resource, 0, 0, color);",
            "}",
            "",
            "/* 从资源 3 的 757x383 图集中裁剪 43x40 的当前元素图片。 */",
            "static void draw_current_element_highlight(void) /* 0x81c01204 */",
            "{",
            "    int source_x, source_y;",
            "    void *resource = get_dlx_resource(3, g_dlx_table);",
            "    if (!resource)",
            "        return;",
            "    element_atlas_position(g_selected_element, &source_x, &source_y);",
            "    system_gui_draw_vx_region(g_current_draw, 105, 155, 43, 40,",
            "                              resource, source_x, source_y);",
            "    system_res_trace(str_0000d24c, 0);",
            "}",
            "",
            "static void draw_periodic_table(WindowHandle frame)",
            "{",
            "    g_current_draw = system_gui_object_draw_begin(frame);",
            "    g_current_resource = get_dlx_resource(1, g_dlx_table);",
            "    if (g_current_resource)",
            "        system_gui_draw_vx(g_current_draw, 0, 0, 240, 320, g_current_resource);",
            "    draw_current_element_tile();",
            "    draw_current_element_highlight();",
            "    system_gui_object_draw_end(frame, g_current_draw);",
            "}",
            "",
            "static void draw_element_detail(WindowHandle frame)",
            "{",
            "    g_current_draw = system_gui_object_draw_begin(frame);",
            "    g_current_resource = get_dlx_resource(6, g_dlx_table);",
            "    if (g_current_resource)",
            "        system_gui_draw_vx(g_current_draw, 0, 290, 240, 30, g_current_resource);",
            "    g_current_resource = get_dlx_resource(7, g_dlx_table);",
            "    if (g_current_resource)",
            "        system_gui_draw_vx(g_current_draw, 0, 0, 240, 25, g_current_resource);",
            "    system_gui_object_draw_end(frame, g_current_draw);",
            "}",
            "",
            "/* 0x0060：读取当前元素正文，创建 dictview 并设置资源 5 背景。 */",
            "static void initialize_element_detail(WindowHandle frame)",
            "{",
            "    uint8_t *state;",
            "    word_t surface;",
            "",
            "    load_element_description(g_selected_element);",
            "    g_dict_view = system_gui_create_window_candidate(str_0000d200, \"\", 0x08080000u,",
            "                                                     0, 0x85, 0, 0x19, 0xf0, 0x109,",
            "                                                     frame, 0);",
            "    if (g_dict_view == (word_t)-1) {",
            "        system_res_trace(str_0000d224, 0);",
            "        return;",
            "    }",
            "    system_gui_active_frame_set(g_dict_view);",
            "",
            "    if (g_using_fallback_dlx == 1) {",
            "        surface = system_gui_draw_object_create(15);",
            "        system_gui_send(g_dict_view, 0x0848, surface, 0);",
            "    } else {",
            "        state = (uint8_t *)(uintptr_t)system_gui_object_userdata(g_dict_view);",
            "        if (state) {",
            "            *(uint16_t *)(void *)(state + 0x1c) = 0;",
            "            state[0x1e] = 1;",
            "        }",
            "    }",
            "",
            "    g_current_resource = get_dlx_resource(5, g_dlx_table);",
            "    if (g_current_resource) {",
            "        system_gui_send(g_dict_view, 0xf0ddu, 0, (word_t)g_current_resource);",
            "        system_res_trace(str_0000d210, 0);",
            "    }",
            "    system_gui_send(g_dict_view, 0x080a, 0x10, (word_t)g_hx_scratch);",
            "}",
            "",
            "static uint32_t hit_test_periodic_table(uint32_t x, uint32_t y)",
            "{",
            "    uint32_t element;",
            "    int tile_x, tile_y;",
            "    for (element = 1; element <= 118; ++element) {",
            "        element_tile_position(element, &tile_x, &tile_y);",
            "        /* 原命中框相对 16x16 标记坐标内缩 2 像素，尺寸为 12x12。 */",
            "        if (x >= (uint32_t)(tile_x + 2) && x < (uint32_t)(tile_x + 14) &&",
            "            y >= (uint32_t)(tile_y + 2) && y < (uint32_t)(tile_y + 14))",
            "            return element;",
            "    }",
            "    return 0;",
            "}",
            "",
            "/* 用整屏资源 2/1 的同一区域显示按钮按下和恢复状态。 */",
            "static void flash_screen_button(WindowHandle frame, int x, int y, int width, int height)",
            "{",
            "    g_current_draw = system_gui_begin_draw(frame);",
            "    system_gui_present(1);",
            "    g_current_resource = get_dlx_resource(2, g_dlx_table);",
            "    if (g_current_resource)",
            "        system_gui_draw_vx_region(g_current_draw, x, y, width, height,",
            "                                  g_current_resource, x, y);",
            "    system_delay(0xc350u);",
            "    g_current_resource = get_dlx_resource(1, g_dlx_table);",
            "    if (g_current_resource)",
            "        system_gui_draw_vx_region(g_current_draw, x, y, width, height,",
            "                                  g_current_resource, x, y);",
            "    system_gui_present(0);",
            "    system_gui_end_draw(g_current_draw);",
            "}",
            "",
            "static void open_element_detail(WindowHandle parent)",
            "{",
            "    if (g_selected_element >= 115) {",
            "        system_gui_msgbox(parent, str_0000d258, str_0000d26c, 0);",
            "    } else {",
            "        g_element_frame = run_standard_window(element_detail_window_proc);",
            "    }",
            "    system_gui_object_op(parent, 0, 0);",
            "}",
            "",
            "/* 元素详情窗口过程；0x0060 初始化正文，0x00b1 执行重绘。 */",
            "static word_t element_detail_window_proc(WindowHandle frame, uint32_t msg, word_t wparam, word_t lparam) /* 0x81c006d0 */",
            "{",
            "    uint32_t x = (uint32_t)lparam & 0xffffu;",
            "    uint32_t y = ((uint32_t)lparam >> 16) & 0xffffu;",
            "    uint32_t command = (uint32_t)wparam & 0xffffu;",
            "",
            "    switch (msg) {",
            "    case 0x0001: /* 触摸坐标 */",
            "        if (x >= 199 && x <= 212 && y >= 5 && y <= 19)",
            "            return system_gui_notify(frame, 0x07fd, 0, 0);",
            "        if (x >= 217 && x <= 233 && y >= 5 && y <= 19)",
            "            return system_gui_notify(frame, 0x0066, 0, 0);",
            "        if (x >= 6 && x <= 24 && y >= 296 && y <= 316) {",
            "            flash_screen_button(frame, 5, 296, 19, 20);",
            "            return system_gui_notify(frame, 0x0066, 0, 0);",
            "        }",
            "        if (x >= 216 && x <= 234 && y >= 296 && y <= 316) {",
            "            flash_screen_button(frame, 215, 296, 20, 20);",
            "            return system_gui_notify(frame, 0x0066, 0, 0);",
            "        }",
            "        return system_gui_default_proc(frame, msg, wparam, lparam);",
            "    case 0x0010: /* 键盘/命令消息，命令号位于 wParam */",
            "        if (command == 1)",
            "            return system_gui_notify(frame, 0x0066, 0, 0);",
            "        if (command == 0x69)",
            "            return system_gui_send(g_dict_view, 0x0010, 0x68, 0);",
            "        if (command == 0x6a)",
            "            return system_gui_send(g_dict_view, 0x0010, 0x6d, 0);",
            "        return system_gui_default_proc(frame, msg, wparam, lparam);",
            "    case 0x0060: /* 初始化正文与 dictview */",
            "        initialize_element_detail(frame);",
            "        return system_gui_default_proc(frame, msg, wparam, lparam);",
            "    case 0x00b1: /* 重绘 */",
            "        draw_element_detail(frame);",
            "        return system_gui_default_proc(frame, msg, wparam, lparam);",
            "    case 0x07fd: /* 帮助 */",
            "        system_gui_help_candidate(frame, str_0000d06c);",
            "        return system_gui_default_proc(frame, msg, wparam, lparam);",
            "    case 0x0844: /* 一键返回：关闭详情和周期表窗口 */",
            "        system_gui_notify(frame, 0x0066, 0, 0);",
            "        return system_gui_notify(g_periodic_frame, 0x0066, 0, 0);",
            "    case 0x0066: /* 销毁详情控件与窗口 */",
            "        if (g_dict_view) {",
            "            system_gui_destroy(g_dict_view);",
            "            g_dict_view = 0;",
            "        }",
            "        system_gui_frame_stop(frame);",
            "        return system_gui_frame_release(frame);",
            "    default:",
            "        return system_gui_default_proc(frame, msg, wparam, lparam);",
            "    }",
            "}",
            "",
            "/* 顶层周期表窗口过程；0x0010 是二级命令，0x00b1 才是重绘消息。 */",
            "static word_t periodic_table_window_proc(WindowHandle frame, uint32_t msg, word_t wparam, word_t lparam) /* 0x81c014dc */",
            "{",
            "    uint32_t command = (uint32_t)wparam & 0xffffu;",
            "    uint32_t x = (uint32_t)lparam & 0xffffu;",
            "    uint32_t y = ((uint32_t)lparam >> 16) & 0xffffu;",
            "    uint32_t element;",
            "",
            "    switch (msg) {",
            "    case 0x0001: /* 触摸坐标 */",
            "        if (x >= 105 && x <= 148 && y >= 155 && y <= 195) {",
            "            open_element_detail(frame);",
            "            return system_gui_default_proc(frame, msg, wparam, lparam);",
            "        }",
            "        if (x >= 199 && x <= 212 && y >= 5 && y <= 19)",
            "            return system_gui_notify(frame, 0x07fd, 0, 0);",
            "        if (x >= 217 && x <= 233 && y >= 5 && y <= 19)",
            "            return system_gui_notify(frame, 0x0066, 0, 0);",
            "        if (x >= 6 && x <= 24 && y >= 296 && y <= 316) {",
            "            flash_screen_button(frame, 5, 296, 19, 20);",
            "            return system_gui_notify(frame, 0x0066, 0, 0);",
            "        }",
            "        if (x >= 216 && x <= 234 && y >= 296 && y <= 316) {",
            "            flash_screen_button(frame, 215, 296, 20, 20);",
            "            return system_gui_notify(frame, 0x0066, 0, 0);",
            "        }",
            "        element = hit_test_periodic_table(x, y);",
            "        if (element) {",
            "            g_selected_element = element;",
            "            system_gui_object_op(frame, 0, 0);",
            "        }",
            "        return system_gui_default_proc(frame, msg, wparam, lparam);",
            "    case 0x0010: /* 键盘/命令消息 */",
            "        if (command == 1)",
            "            return system_gui_notify(frame, 0x0066, 0, 0);",
            "        if (command == 0x1c) {",
            "            open_element_detail(frame);",
            "            return system_gui_default_proc(frame, msg, wparam, lparam);",
            "        }",
            "        if (command == 0x67)",
            "            g_selected_element = k_element_neighbors[g_selected_element][0];",
            "        else if (command == 0x6c)",
            "            g_selected_element = k_element_neighbors[g_selected_element][1];",
            "        else if (command == 0x69)",
            "            g_selected_element = g_selected_element == 1 ? 118 : g_selected_element - 1;",
            "        else if (command == 0x6a)",
            "            g_selected_element = g_selected_element == 118 ? 1 : g_selected_element + 1;",
            "        else",
            "            return system_gui_default_proc(frame, msg, wparam, lparam);",
            "        system_gui_object_op(frame, 0, 0);",
            "        return system_gui_default_proc(frame, msg, wparam, lparam);",
            "    case 0x0060: /* 初始化 HX 正文偏移表 */",
            "        load_hx_offset_table();",
            "        return system_gui_default_proc(frame, msg, wparam, lparam);",
            "    case 0x00b1: /* 完整重绘 */",
            "        draw_periodic_table(frame);",
            "        return system_gui_default_proc(frame, msg, wparam, lparam);",
            "    case 0x07fd: /* 帮助 */",
            "        system_gui_help_candidate(frame, str_0000ce28);",
            "        return system_gui_default_proc(frame, msg, wparam, lparam);",
            "    case 0x0844:",
            "        return system_gui_notify(frame, 0x0066, 0, 0);",
            "    case 0x0066: /* 释放 DLX 并关闭主窗口 */",
            "        free_dlx_resource_table(g_dlx_table);",
            "        g_dlx_table = NULL;",
            "        system_gui_frame_stop(frame);",
            "        return system_gui_frame_release(frame);",
            "    default:",
            "        return system_gui_default_proc(frame, msg, wparam, lparam);",
            "    }",
            "}",
            "",
            "/* 选择资源包、加载数据、创建主窗口并完成清理。 */",
            "static int element_table_main(void) /* 0x81c0218c */",
            "{",
            "    FileHandle probe;",
            "",
            "    /* GUI+0x7c0 的结果同时保存为资源模式标志。 */",
            "    g_using_fallback_dlx = (uint32_t)system_gui_mode_query_candidate();",
            "    g_dlx_table = load_dlx_resource_file(g_using_fallback_dlx ?",
            "                                                 str_0000d334 : str_0000d280);",
            "    if (!g_dlx_table) {",
            "        system_gui_msgbox(0, str_0000d308, str_0000d26c, 0);",
            "        system_gui_notify(g_periodic_frame, 0x0066, 0, 0);",
            "        return -1;",
            "    }",
            "",
            "    /* 主函数只验证数据文件存在；偏移与正文由窗口逻辑按需读取。 */",
            "    probe = system_fs_open(str_0000d1cc, \"rb\");",
            "    g_data_file = probe;",
            "    if (!probe) {",
            "        system_gui_message_box_rect(30, 100, 180, 120, 0,",
            "                                    str_0000d2d4, str_0000d26c);",
            "        return -2;",
            "    }",
            "    system_fs_close(probe);",
            "",
            "    g_periodic_frame = run_standard_window(periodic_table_window_proc);",
            "    return g_periodic_frame == (WindowHandle)-1 ? -3 : 0;",
            "}",
            "",
        ]
    )


def emit_remaining_functions(
    lines: list[str], functions: list[dict], api_calls: list[dict], xrefs: dict
) -> None:
    special = {
        0x81C00020, 0x81C00050, 0x81C001A0, 0x81C002F8, 0x81C004BC,
        0x81C00648, 0x81C00654, 0x81C0069C, 0x81C00F7C, 0x81C01204,
        0x81C027D0, 0x81C02854,
        0x81C0280C, 0x81C02884, 0x81C02AD8, 0x81C02AF8, 0x81C02B60,
        0x81C02BD0, 0x81C03480, 0x81C034A0,
        0x81C03320, 0x81C034D0, 0x81C034F0, 0x81C03668, 0x81C036B8,
        0x81C036E0,
        0x81C006D0, 0x81C014DC, 0x81C0218C, 0x81C0240C, 0x81C02598,
        0x81C026C0,
    }
    apis_by_function: dict[int, list[dict]] = defaultdict(list)
    for call in api_calls:
        apis_by_function[int(call["function_va"])].append(call)

    calls = xrefs.get("direct_calls", [])
    strings = xrefs.get("string_xrefs", [])
    for function in functions:
        va = int(function["va"])
        if va in special:
            continue
        start = int(function["file_offset"])
        end = int(function["candidate_end_off"])
        name = name_for_va(va)
        if name.endswith("_block"):
            continue
        direct = [c for c in calls if start <= int(c["file_offset"]) < end]
        refs = [s for s in strings if start <= int(s["use_off"]) < end]
        confidence = function.get("confidence", "unknown")
        description = FUNCTION_COMMENTS.get(va)
        if description is None and confidence == "call_target_or_api_context":
            description = (
                "窗口过程内部的候选代码块；名称按该块调用的系统 API 和邻近控制流推测，"
                "不应视为独立 C 函数。"
            )
        elif description is None:
            description = "函数用途按调用关系和指令形状推测，仍需动态验证。"
        lines.extend(
            [
                f"/* {description}",
                f" * 边界可信度：{confidence}；原始地址：0x{va:08x}。",
                " */",
                f"static word_t {name}(void)",
                "{",
                f"    /* file+0x{start:x}..0x{end:x}, VA 0x{va:08x}, {end - start} bytes.",
            ]
        )
        if apis_by_function[va]:
            lines.append("     * Recovered API call order:")
            for call in sorted(apis_by_function[va], key=lambda item: int(item["jalr_off"])):
                names = "/".join(call.get("sdk_names", [])) or "unknown"
                lines.append(
                    f"     *   file+0x{int(call['jalr_off']):x}: {call['table']}+0x{int(call['api_offset']):03x} {names}"
                )
        if direct:
            lines.append("     * Direct internal calls:")
            for call in direct:
                target = int(call["target_va"])
                lines.append(
                    f"     *   file+0x{int(call['file_offset']):x}: {name_for_va(target)} (0x{target:08x})"
                )
        if refs:
            lines.append("     * Referenced strings:")
            for ref in refs:
                lines.append(
                    f'     *   file+0x{int(ref["use_off"]):x}: "{short_text(ref["text"])}"'
                )
        lines.extend(
            [
                "     * Structured branches, argument types and return type remain uncertain.",
                "     */",
                f"    return unresolved(0x{va:08x}u);",
                "}",
                "",
            ]
        )


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a C-like reconstruction of Element Table BDA")
    parser.add_argument("analysis_dir", type=Path)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()

    root = args.analysis_dir
    functions_doc = load_json(root / "element_table_functions.json")
    api_doc = load_json(root / "element_table_api_calls.json")
    strings_doc = load_json(root / "element_table_strings_interesting.json")
    xrefs_doc = load_json(root / "element_table_xrefs.json")
    output = args.output or root / "element_table_reconstructed.c"
    system_header = output.with_name("system.h")
    source = Path(functions_doc["source"])
    if not source.is_absolute():
        source = root.parents[1] / source
    navigation_pairs = load_navigation_pairs(source)

    functions = functions_doc["functions"]
    lines: list[str] = []
    emit_prelude(lines, functions_doc["source"])
    emit_strings(lines, strings_doc["strings"])
    emit_prototypes(lines, functions)
    emit_semantic_core(lines, navigation_pairs)
    emit_remaining_functions(lines, functions, api_doc["calls"], xrefs_doc)
    emit_system_header(system_header)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {system_header}")
    print(f"wrote {output} ({len(lines)} lines, {len(functions)} recovered labels)")


if __name__ == "__main__":
    main()
